### ISSUE TITLE
Reader.find入参校验不严谨

### ISSUE THREAD

**Issue by GSephrioth** [ipipdotnet/ipdb-java#8]
IPAddressUtil.textToNumericFormatV4() 和 IPAddressUtil.textToNumericFormatV6 已被弃用，不能正确判断 IPv4 和 IPv6 的格式。
输入参数为 “1.2”，“1.4.2” 时返回数据异常。

**Comment by ilsanbao** [comment]
@GSephrioth  IP是否合法请在传入find方法前自行检查，IPAddressUtil.textToNumericFormatV4() 和 IPAddressUtil.textToNumericFormatV6 主要功能是转 IP 到 byte[]
